### ISSUE TITLE
gv.WMTS zoom in causes "bounce back" behavior

### ISSUE THREAD

**Issue by digitaltopo** [holoviz/geoviews#111]
Strange behavior when zooming in on a `gv.WMTS` slippy map where the map flickers and bounces back to less zoomed in zoom levels. See gif:

![geoviews-zoom](https://user-images.githubusercontent.com/1680796/34066219-707bbeba-e1c0-11e7-8ced-1bfb4b2165de.gif)

Code:
```
import geoviews as gv
from bokeh.models import WMTSTileSource

 gv.WMTS(WMTSTileSource(url='http://c.tile.openstreetmap.org/{Z}/{X}/{Y}.png'))
```

Same behavior with other tile sources. Looking in network tab, all tile image file requests are 200.

holoviews 1.9.2
geoviews 1.4.0
bokeh 0.12.11

`gv.WMTS` is based off of `owslib.wmts`'s  `WebMapTileService`

**Comment by jbednar** [comment]
Can you try bokeh 0.12.13?

**Comment by digitaltopo** [comment]
Same behavior with bokeh `0.12.13`

**Comment by jbednar** [comment]
Damn.

**Comment by jbednar** [comment]
I haven't reproduced this problem myself, but a colleague of mine suggests that the problem could be triggered when the map tiles reach a level where there is no further resolution available, with a fallback that is very confusing in this case.  If so, that would need to be fixed in Bokeh, not GeoViews.  

My personal feeling is that when that happens, whatever map tile zoom level was last successfully retrieved should simply be zoomed up indefinitely as an image, no matter how big the pixels get. For an online map service, it makes sense to clamp the maximum zoom level, but in Bokeh, map tiles are  usually just a backdrop for the real data, and whether the map tiles are available at that resolution or not we'd still need to be able to zoom in to our real data.  

@philippjfr, does this sound like a reasonable explanation of this issue?  If so, we should file this as an issue on the Bokeh site and then try to fix it.

**Comment by philippjfr** [comment]
Sounds possible, although it seems the zoom level is not nearly sufficient to be running out of resolution. I've also not been able to reproduce, so it might be worth knowing which browser this is occurring with.

**Comment by digitaltopo** [comment]
I second the above, it's definitely not due to bottoming out on available zoom level tiles. 

Have experienced in following browsers:
* Chromium  63.0.3239.84 
* Firefox (Quantum) 58.0b3 (64-bit)

**Comment by philippjfr** [comment]
Appears to be mostly fixed in using bokeh 0.12.14dev, would you mind trying? You can install it with:

```
conda install -c bokeh/label/dev bokeh
```

**Comment by digitaltopo** [comment]
Sorry to resurrect this, but noticed this happening again in a recent notebook.

`HoloViews: 1.11.3`
`GeoViews: 1.6.2`
`Bokeh: 1.0.4`

**Comment by ahuang11** [comment]
I also am experiencing this stretchy/bouncy behavior.
bokeh                              1.1.0
geoviews                           1.6.5
datashader                         0.6.9
hvplot                             0.5.2
holoviews                          1.12.6
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15331990/68260945-22af3b80-0004-11ea-8888-c6da2f7efe21.gif)

**Comment by philippjfr** [comment]
My best suggestion here is for HoloViews data aspect handling code to become slightly more tolerant of aspect distortion, e.g. going from 1% tolerance to 5% eliminates the bouncing for me.
