### ISSUE TITLE
hvplot/utils also requires pyproj

### ISSUE THREAD

**Issue by nbecker** [holoviz/geoviews#299]
In util.py: process_crs, we see:

```
    try:
        import cartopy.crs as ccrs
        import geoviews as gv # noqa
        import pyproj
    except:
        raise ImportError('Geographic projection support requires GeoViews and cartopy.')
```

But pyproj is not mentioned, and this is exactly what I was missing.

**Comment by philippjfr** [comment]
Thanks for tracking that down, I had assumed pyproj was installed alongside cartopy. I'll push a fix to hvplot and then tag a micro release later today or tomorrow.

**Comment by KarenChen9999** [comment]
I ran into the same issues, 
```
/apps/opt/anaconda3/envs/geo_env/lib/python3.8/site-packages/hvplot/util.py in process_crs(crs)
    182         import pyproj
    183     except:
--> 184         raise ImportError('Geographic projection support requires GeoViews and cartopy.')
    185 
    186     if crs is None:

ImportError: Geographic projection support requires GeoViews and cartopy.
```
my package versions are:
geopandas                 0.8.2              pyhd8ed1ab_0    conda-forge
geoviews                  1.8.1                    pypi_0    pypi
hvplot                    0.7.0              pyhd3deb0d_0    conda-forge

**Comment by jbednar** [comment]
@philippjfr , it looks like you made a change in how pyproj is handled in `process_crs` in geoviews/util.py, but (despite the repo this issue is filed on) the issue reported here was about `process_crs` in hvplot/util.py, not GeoViews. The hvPlot version still tries to import pyproj as it did before, and so hvPlot users with geoviews but without pyproj would presumably still see this message, which it sounds like is what @KarenChen9999  is reporting.
