### ISSUE TITLE
Update or delete roadmap

### ISSUE THREAD

**Issue by jsignell** [holoviz/geoviews#379]
The roadmap on geoviews.org is from 2018-06. I propose that we delete it.

**Comment by jbednar** [comment]
I agree we should delete it, mostly because we've now actually done nearly every bit of it!  Before we delete it, should probably open a feature-request issue for anything in the roadmap that we haven't actually done.  Cartograms are the only thing that jump out to me, apart from 3D viz that's already mentioned in a PR and/or issue about CesiumJS.  At that point, we could consider having a different sort of roadmap that is simply a link to a github milestone, and then we could tag issues with a `wishlist` tag or similar so that the collection of issues in that milestone becomes the roadmap (insofar as we do have any roadmap!).

**Comment by jsignell** [comment]
I've deleted it from the dev website. I imagine you or @philippjfr will have a better sense of what should graduate into feature requests.

**Comment by jbednar** [comment]
Ok, I'll make some issues out of what's left over from the roadmap.

**Comment by jbednar** [comment]
I've made issues with everything left, some of which are on Datashader.  The roadmap is now available by looking at the issues labeled `wishlist`: https://github.com/holoviz/geoviews/issues?q=is%3Aopen+is%3Aissue+label%3Awishlist

**Comment by jsignell** [comment]
Thanks!
