### ISSUE TITLE
annotators wont work in geoviews 

### ISSUE THREAD

**Issue by suvarchal** [holoviz/geoviews#462]
Annotators example at https://geoviews.org/user_guide/Annotators.html doesn't  work,  annotators  
using holoviews works though. 

#### ALL software version info
python=3.7
bokeh=2.0.2
holoviews=1.13.2
geoviews=1.8.1 
OS: Linux, 
Browsers: Firefox or Chrome

to be sure of environment issues, I tried on binder using repo: https://github.com/suvarchal/geoviews_bug and used it for examples below. 

#### Description of expected behavior and the observed behavior
Expected it to work like holoviews annotators example but doesn't. JS Console gives two errors based on if holoviews was used before geoviews snippet or not. 

#### Complete, minimal, self-contained example code that reproduces the issue

Basically, the  code from the docs, https://geoviews.org/user_guide/Annotators.html.
If it helps here are binder links to the notebooks.
Example 1:
 [![Binder geoviews_bug.ipynb](https://mybinder.org/badge_logo.svg)](
https://gesis.mybinder.org/binder/v2/gh/suvarchal/geoviews_bug/0f559ba98fc402566e934dd626a0401fe0153962?filepath=geoviews_bug.ipynb
)

Example 2:
 [![Binder geoviews_holoviews_bug.ipynb](https://mybinder.org/badge_logo.svg)](
https://gesis.mybinder.org/binder/v2/gh/suvarchal/geoviews_bug/0f559ba98fc402566e934dd626a0401fe0153962?filepath=geoviews_holoviews_bug.ipynb
)

#### Browser JavaScript console output
`
 Error: Model 'geoviews.models.custom_tools.ClearTool' does not exist. This could be due to a widget or a custom model not being registered before first usage.
`
or
`
Error: Model 'geoviews.models.custom_tools.CheckpointTool' does not exist. This could be due to a widget or a custom model not being registered before first usage. 
`

**Comment by philippjfr** [comment]
That sounds like an issue with the GeoViews package. Could you try installing GeoViews from conda-forge to see if that fixes it? In the meantime I'll have to test the package on the pyviz channel and then release a new version if necessary.

**Comment by suvarchal** [comment]
issue still remains with geoviews from conda-forge.

conda took forever to solve its magic, tried out [mamba](https://quantstack.net/mamba.html) and that was quick.

**Comment by philippjfr** [comment]
Should finally be fixed. Please reopen if this still happens.

**Comment by weiji14** [comment]
This seems to be broken again. I'm getting no annotation tools showing up, and the same `Uncaught Error: Model 'geoviews.models.custom_tools.ClearTool' does not exist. This could be due to a widget or a custom model not being registered before first usage.` message in the console.

![image](https://user-images.githubusercontent.com/23487320/131199654-436eb79d-40c8-46c3-a3a5-89ddd0301556.png)

Binder link to reproduce: [![Binder](https://binder.pangeo.io/badge_logo.svg)](https://binder.pangeo.io/v2/gist/weiji14/f67232a393d7451a49a715aa9f40419c/master?filepath=geoviews.ipynb)

Dependencies:

- python=3.8
- bokeh=2.3.3
- holoviews=1.14.5
- geoviews=1.9.1
- OS=Linux
- Browser=Firefox

**Comment by sbonaime** [comment]
@philippjfr Can you reopen this issue ? I have the same error as @weiji14 
thanks

**Comment by philippjfr** [comment]
Please open a new issue with the versions of the various libraries you are using.
