### ISSUE TITLE
Fix all the shapely deprecation warnings before shapely 2 is released

### ISSUE THREAD

**Issue by maximlt** [holoviz/geoviews#592]
There are [apparently](https://github.com/holoviz/geoviews/pull/570#issuecomment-1272529723) some deprecation warnings that were missed, including `ShapelyDeprecationWarning: STRtree will be changed in 2.0.0 and will not be compatible with versions < 2. tree = STRtree(geoms)` emitted when `resample_geometry` is executed (not part of the test suite).

Thanks @TheoMathurin! Do you feel like making a PR to fix this warning?

**Comment by TheoMathurin** [comment]
Not sure I'm the person best suited for the job as I've never directly used shapely but I can take a look!

**Comment by maximlt** [comment]
Thanks! Any contribution is deeply appreciated :)

**Comment by TheoMathurin** [comment]
No mention of STRtree in the 1.8 to 2.0 [migration guide](https://shapely.readthedocs.io/en/stable/migration.html). Too bad the warning is so vague compared to others which in some instances indicate a way forward.

Looking for clues elsewhere.

**Comment by TheoMathurin** [comment]
I don't think the deprecation warning can be avoided. It's issued at instantiation (`tree = STRtree(geoms)`) and the way to instantiate will not change (except for the introduction of an optional `node_capacity` kwarg). And in fact the warning itself says that the new API will not be compatible with versions < 2.0, meaning you have to wait for 2.0 to adapt the code.

The main change [will be](https://github.com/shapely/shapely/blob/a716551eb0b9956bb5f860247ad1b4e357ec802e/docs/release/2.x.rst#strtree-api-changes-and-improvements) that operations such as `query` or `nearest` will return indices of the input geometries instead of the geometries themselves. This means that the change needed will revolve around the `g` variable ([here](https://github.com/holoviz/geoviews/blob/33876c88b166755774451055869704af65786ab4/geoviews/operation/resample.py#L167)).

**Comment by maximlt** [comment]
Thanks for digging into that @TheoMathurin ! I think a first good step would be to write some tests that exercice `resample_geometry`, which would make adapting it to Shapely 2 easier.

**Comment by TheoMathurin** [comment]
Yes, I'll try to take a look at the test suite.
