### ISSUE TITLE
Use explicit web links for example data

### ISSUE THREAD

**Issue by droumis** [holoviz/geoviews#599]
A user posted in Discourse about not knowing where to find the data ("ensemble.nc") for the GeoViews homepage example. The solution is that users have to run `geoviews examples` to download the example data before being able to run the homepage code. We received a follow-up about this issue in our user survey requesting that we 'use only publicly available data' for docs examples. I'm assuming they are suggesting referencing data in the example through an explicit web link rather than a local system file.

What are the pros, cons of this suggested web link data approach vs what we do now? Should we just work to clarify the homepage and installation instructions? Any cases where we definitely would not want to use an explicit link to access data?

**Comment by jbednar** [comment]
I wouldn't interpret a request to 'use only publicly available data' to mean 'download from the web' in particular. Instead, I think it's just a request to be more transparent about where data comes from, which could be achieved by printing the source URL where data was (originally) obtained when installing data, so that people can trace where it comes from.

Using an external link to actually get the data will eventually fail and break our examples and often our tests, and I don't think we should rely on external servers remaining up and and the same address. But that's separate from whether we should package the data or fetch it dynamically (from our own servers), which is a different issue with a lot of subtle pros and cons.
